namespace CsJvm.Models.ClassFileFormat.Methods
{
    /// <summary>
    /// Method access and property flags
    /// </summary>
    [Flags]
    public enum MethodAccessAndPropertyFlags
    {
        /// <summary>
        /// Declared public; may be accessed from outside its package.
        /// </summary>
        ACC_PUBLIC = 0x0001,

        /// <summary>
        /// Declared private; accessible only within the defining class.
        /// </summary>
        ACC_PRIVATE = 0x0002,

        /// <summary>
        /// Declared protected; may be accessed within subclasses.
        /// </summary>
        ACC_PROTECTED = 0x0004,

        /// <summary>
        /// Declared static.
        /// </summary>
        ACC_STATIC = 0x0008,

        /// <summary>
        /// Declared final; must not be overridden.
        /// </summary>
        ACC_FINAL = 0x0010,

        /// <summary>
        /// Declared synchronized; invocation is wrapped by a monitor use.
        /// </summary>
        ACC_SYNCHRONIZED = 0x0020,

        /// <summary>
        /// A bridge method, generated by the compiler.
        /// </summary>
        ACC_BRIDGE = 0x0040,

        /// <summary>
        /// Declared with variable number of arguments.
        /// </summary>
        ACC_VARARGS = 0x0080,

        /// <summary>
        /// Declared native; implemented in a language other than Java.
        /// </summary>
        ACC_NATIVE = 0x0100,

        /// <summary>
        /// Declared abstract; no implementation is provided.
        /// </summary>
        ACC_ABSTRACT = 0x0400,

        /// <summary>
        /// Declared strictfp; floating-point mode is FP-strict.
        /// </summary>
        ACC_STRICT = 0x0800,

        /// <summary>
        /// Declared synthetic; not present in the source code.
        /// </summary>
        ACC_SYNTHETIC = 0x1000
    }
}
